# Pandas - Series and DataFrames

### By Alka Pandey

Pandas has two datastructures: Series and Dataframes

In [34]:
# Import pandas

import pandas as pd

In [35]:
# Creating series from a list

s1 = pd.Series([10,20,30,40,50])
print(s1)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [36]:
type(s1) #checking the type of s1 series created

pandas.core.series.Series

In [37]:
# creating an empty series

s2 = pd.Series()
print(s2)

Series([], dtype: object)

In [38]:
# create a series from numpy array

import numpy as np
arr = np.array([4,2,6,8,9,10])
serie = pd.Series(arr)
print(serie)

0     4
1     2
2     6
3     8
4     9
5    10
dtype: int64

In [39]:
# create a pandas series from a dictionary:

data = {"A":10,"B":40,"X":60,"Y":90,"Z":100}
s4 = pd.Series(data)
print(s4)

A     10
B     40
X     60
Y     90
Z    100
dtype: int64

In [40]:
print(s4.iloc[0]) #iloc is used to access certain index location

10

In [41]:
print(s4.loc["B"]) #loc is used to access value based on label index

40

In [42]:
s4.iloc[0:4]

A    10
B    40
X    60
Y    90
dtype: int64

In [43]:
s4.loc["A":"Y"]

A    10
B    40
X    60
Y    90
dtype: int64

In [44]:
list1 = [1,4,5,6,7]
print(list1[-1])

7

### Filter or subset

In [45]:
h1 = pd.Series([3,4,5,6,7,8,10,1,2,3,4,5,667,7,88,8,99,9])
print(h1)

0       3
1       4
2       5
3       6
4       7
5       8
6      10
7       1
8       2
9       3
10      4
11      5
12    667
13      7
14     88
15      8
16     99
17      9
dtype: int64

In [46]:
save = h1[h1>=8]
save

5       8
6      10
12    667
14     88
15      8
16     99
17      9
dtype: int64

In [47]:
save2 = h1[(h1>=8) & (h1<=500)] #filtering on two conditions
save2

5      8
6     10
14    88
15     8
16    99
17     9
dtype: int64

In [48]:
type(save2) #check the type of our series

pandas.core.series.Series

In [50]:
new = save2.reset_index(drop=True) #To reset the index
new

0     8
1    10
2    88
3     8
4    99
5     9
dtype: int64

In [51]:
sum(new) #Using simple operations like sum on series

222

## DataFrames

In [88]:
# Creating a dataframe from a list

lis = [80,80,50,20,70]

df = pd.DataFrame(lis)
df

    0
0  80
1  80
2  50
3  20
4  70

In [89]:
df.columns = ["Col1"] #Renaming the column

In [90]:
df

   Col1
0    80
1    80
2    50
3    20
4    70

In [ ]:
# Create a dataframe from a list of dictionary

In [96]:
ldict1 = [{"a":10,"b":30,"c":77},{"a":15,"b":99,"d":100},{"a":155,"b":999,"c":1000},{"a":655,"b":9,"c":109,"d":44}]
df2 = pd.DataFrame(ldict1)
df2

     a    b       c      d
0   10   30    77.0    NaN
1   15   99     NaN  100.0
2  155  999  1000.0    NaN
3  655    9   109.0   44.0

In [100]:
# Rename columns - option 1

df3 = df2.rename(columns ={"c":"newcol1","d":"newcol2"})

In [101]:
# Rename columns - option 2 with inplace, changes are reflected in the original dataframe

df2.rename(columns ={"c":"newcol1","d":"newcol2"},inplace=True)

In [102]:
df2

     a    b  newcol1  newcol2
0   10   30     77.0      NaN
1   15   99      NaN    100.0
2  155  999   1000.0      NaN
3  655    9    109.0     44.0

In [103]:
# Rename columns - Option 3: columns function and assign

df2.columns = ["A","B","C","D"]
df2

     A    B       C      D
0   10   30    77.0    NaN
1   15   99     NaN  100.0
2  155  999  1000.0    NaN
3  655    9   109.0   44.0

In [53]:
# Reading files in pandas - dataframe if file is in the same location as your notebook

data = pd.read_csv("datademo.csv")

In [54]:
data

   StudentID  StudentName  Class  Age    Subject
0        101      Kamlesh      5   10      Maths
1        102       MadhuS      6   12    English
2        103      Aniketh      1   12  Geography
3        104       Rashmi      8   15      Maths
4        105        Satya     12   12    English
5        106    DHANSHREE      4   15    Physics
6        107      Vivek K      5   13    English
7        108      Srishti      7   13  Chemistry
8        109       Vishal      3   10  Chemistry
9        110  Alka Pandey     12    9  Geography

In [58]:
# Reading files in pandas - dataframe if file is NOT in the same location as your notebook
# Provide the full location of the file and using double back slash

data2 = pd.read_csv("C:\\Users\\alkap\\Downloads\\Alka_SmartPC_2026\\PythonForDS_All\\Test\\datademo.csv")

In [59]:
data2

   StudentID  StudentName  Class  Age    Subject
0        101      Kamlesh      5   10      Maths
1        102       MadhuS      6   12    English
2        103      Aniketh      1   12  Geography
3        104       Rashmi      8   15      Maths
4        105        Satya     12   12    English
5        106    DHANSHREE      4   15    Physics
6        107      Vivek K      5   13    English
7        108      Srishti      7   13  Chemistry
8        109       Vishal      3   10  Chemistry
9        110  Alka Pandey     12    9  Geography

In [60]:
data.head() #display first five records of the dataframe

   StudentID StudentName  Class  Age    Subject
0        101     Kamlesh      5   10      Maths
1        102      MadhuS      6   12    English
2        103     Aniketh      1   12  Geography
3        104      Rashmi      8   15      Maths
4        105       Satya     12   12    English

In [61]:
data.tail() #display last five records of the dataframe

   StudentID  StudentName  Class  Age    Subject
5        106    DHANSHREE      4   15    Physics
6        107      Vivek K      5   13    English
7        108      Srishti      7   13  Chemistry
8        109       Vishal      3   10  Chemistry
9        110  Alka Pandey     12    9  Geography

In [62]:
data.head(7) #display first 7 records of the dataframe

   StudentID StudentName  Class  Age    Subject
0        101     Kamlesh      5   10      Maths
1        102      MadhuS      6   12    English
2        103     Aniketh      1   12  Geography
3        104      Rashmi      8   15      Maths
4        105       Satya     12   12    English
5        106   DHANSHREE      4   15    Physics
6        107     Vivek K      5   13    English

In [63]:
data.columns #Get all column names

Index(['StudentID', 'StudentName', 'Class', 'Age', 'Subject'], dtype='object')

In [65]:
type(data["StudentID"]) #Accessing a specific column

pandas.core.series.Series

In [66]:
type(data) #check the type of our dataframe

pandas.core.frame.DataFrame

In [192]:
data[["StudentID"]] #accessing a column in dataframe format

   StudentID
0        101
1        102
2        103
3        104
4        105
5        106
6        107
7        108
8        109
9        110

In [70]:
data["StudentName"].str.upper() #manupulating a column

0        KAMLESH
1         MADHUS
2        ANIKETH
3         RASHMI
4          SATYA
5      DHANSHREE
6        VIVEK K
7        SRISHTI
8         VISHAL
9    ALKA PANDEY
Name: StudentName, dtype: object

In [71]:
data

   StudentID  StudentName  Class  Age    Subject
0        101      Kamlesh      5   10      Maths
1        102       MadhuS      6   12    English
2        103      Aniketh      1   12  Geography
3        104       Rashmi      8   15      Maths
4        105        Satya     12   12    English
5        106    DHANSHREE      4   15    Physics
6        107      Vivek K      5   13    English
7        108      Srishti      7   13  Chemistry
8        109       Vishal      3   10  Chemistry
9        110  Alka Pandey     12    9  Geography

In [72]:
data["StudentName"] = data["StudentName"].str.upper() #converting to upper case and assigning back to column

In [73]:
data

   StudentID  StudentName  Class  Age    Subject
0        101      KAMLESH      5   10      Maths
1        102       MADHUS      6   12    English
2        103      ANIKETH      1   12  Geography
3        104       RASHMI      8   15      Maths
4        105        SATYA     12   12    English
5        106    DHANSHREE      4   15    Physics
6        107      VIVEK K      5   13    English
7        108      SRISHTI      7   13  Chemistry
8        109       VISHAL      3   10  Chemistry
9        110  ALKA PANDEY     12    9  Geography

In [75]:
data["Class"]>=5 #filter condition

0     True
1     True
2    False
3     True
4     True
5    False
6     True
7     True
8    False
9     True
Name: Class, dtype: bool

In [76]:
# filters in dataframe: or subset a dataframe

datafilter = data[data["Class"]>=5]
datafilter

   StudentID  StudentName  Class  Age    Subject
0        101      KAMLESH      5   10      Maths
1        102       MADHUS      6   12    English
3        104       RASHMI      8   15      Maths
4        105        SATYA     12   12    English
6        107      VIVEK K      5   13    English
7        108      SRISHTI      7   13  Chemistry
9        110  ALKA PANDEY     12    9  Geography

In [78]:
data.info() #Info function helps you check information about the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   StudentID    10 non-null     int64
 1   StudentName  10 non-null     object
 2   Class        10 non-null     int64
 3   Age          10 non-null     int64
 4   Subject      10 non-null     object
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

In [80]:
data

   StudentID  StudentName  Class  Age    Subject
0        101      KAMLESH      5   10      Maths
1        102       MADHUS      6   12    English
2        103      ANIKETH      1   12  Geography
3        104       RASHMI      8   15      Maths
4        105        SATYA     12   12    English
5        106    DHANSHREE      4   15    Physics
6        107      VIVEK K      5   13    English
7        108      SRISHTI      7   13  Chemistry
8        109       VISHAL      3   10  Chemistry
9        110  ALKA PANDEY     12    9  Geography

In [81]:
data.describe() #statistical summary of the numerical columns in the dataframe

       StudentID      Class        Age
count   10.00000  10.000000  10.000000
mean   105.50000   6.300000  12.100000
std      3.02765   3.591657   2.024846
min    101.00000   1.000000   9.000000
25%    103.25000   4.250000  10.500000
50%    105.50000   5.500000  12.000000
75%    107.75000   7.750000  13.000000
max    110.00000  12.000000  15.000000

In [84]:
# Create a new column in a dataframe
data["StudentFees"] = data["Class"]*1300
data

   StudentID  StudentName  Class  Age    Subject  StudentFees
0        101      KAMLESH      5   10      Maths         6500
1        102       MADHUS      6   12    English         7800
2        103      ANIKETH      1   12  Geography         1300
3        104       RASHMI      8   15      Maths        10400
4        105        SATYA     12   12    English        15600
5        106    DHANSHREE      4   15    Physics         5200
6        107      VIVEK K      5   13    English         6500
7        108      SRISHTI      7   13  Chemistry         9100
8        109       VISHAL      3   10  Chemistry         3900
9        110  ALKA PANDEY     12    9  Geography        15600

In [86]:
data[data["Age"] == 12]

   StudentID StudentName  Class  Age    Subject  StudentFees
1        102      MADHUS      6   12    English         7800
2        103     ANIKETH      1   12  Geography         1300
4        105       SATYA     12   12    English        15600

In [87]:
data[["StudentID","StudentName"]] #accessing two columns in a dataframe

   StudentID  StudentName
0        101      KAMLESH
1        102       MADHUS
2        103      ANIKETH
3        104       RASHMI
4        105        SATYA
5        106    DHANSHREE
6        107      VIVEK K
7        108      SRISHTI
8        109       VISHAL
9        110  ALKA PANDEY

In [104]:
df2

     A    B       C      D
0   10   30    77.0    NaN
1   15   99     NaN  100.0
2  155  999  1000.0    NaN
3  655    9   109.0   44.0

In [105]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      int64
 1   B       4 non-null      int64
 2   C       3 non-null      float64
 3   D       2 non-null      float64
dtypes: float64(2), int64(2)
memory usage: 260.0 bytes

In [108]:
df2[df2["D"].isna()] #checking null values in a dataframe

     A    B       C   D
0   10   30    77.0 NaN
2  155  999  1000.0 NaN

In [109]:
# changing the index:

d3 = [{"a":10,"b":50},{"a":90,"b":99}]
df33 = pd.DataFrame(d3,index=["First","Second"])

In [110]:
df33

         a   b
First   10  50
Second  90  99

In [111]:
df2

     A    B       C      D
0   10   30    77.0    NaN
1   15   99     NaN  100.0
2  155  999  1000.0    NaN
3  655    9   109.0   44.0

In [113]:
# fillna function to fill the nulls

gg = df2.fillna("0")
gg

     A    B       C      D
0   10   30    77.0      0
1   15   99       0  100.0
2  155  999  1000.0      0
3  655    9   109.0   44.0

In [116]:
df2["D"] = df2["D"].fillna(df2["D"].mean()) #fillna for a column with specific calculation

In [117]:
df2

     A    B       C      D
0   10   30    77.0   72.0
1   15   99     NaN  100.0
2  155  999  1000.0   72.0
3  655    9   109.0   44.0

In [118]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      int64
 1   B       4 non-null      int64
 2   C       3 non-null      float64
 3   D       4 non-null      float64
dtypes: float64(2), int64(2)
memory usage: 260.0 bytes

In [119]:
df2["Discount"] = 10 #creating a new column with a set value
df2

     A    B       C      D  Discount
0   10   30    77.0   72.0        10
1   15   99     NaN  100.0        10
2  155  999  1000.0   72.0        10
3  655    9   109.0   44.0        10

In [121]:
df2.loc[0] #accessing values via loc

A           10.0
B           30.0
C           77.0
D           72.0
Discount    10.0
Name: 0, dtype: float64

In [123]:
df2.iloc[0] #accessing values via iloc

A           10.0
B           30.0
C           77.0
D           72.0
Discount    10.0
Name: 0, dtype: float64

In [124]:
df33

         a   b
First   10  50
Second  90  99

In [125]:
df33.loc["First"]

a    10
b    50
Name: First, dtype: int64

In [127]:
df33.iloc[0]

a    10
b    50
Name: First, dtype: int64

### Concat function:

In [128]:
df1 = pd.DataFrame({"ID":[11,22,33],"Name":["Alice","Bob","Charlie"],"Age":[25,27,26]})
df1

   ID     Name  Age
0  11    Alice   25
1  22      Bob   27
2  33  Charlie   26

In [129]:
df2 = pd.DataFrame({"ID":[44,55,66,77],"Name":["David","Eve","Frank","Gilbert"],"Age":[30,32,35,37]})
df2

   ID     Name  Age
0  44    David   30
1  55      Eve   32
2  66    Frank   35
3  77  Gilbert   37

In [131]:
#stack dataframes vertically

stackvertical = pd.concat([df1,df2],axis=0) #axis=0 means in row wise or stack on top of other
stackvertical

   ID     Name  Age
0  11    Alice   25
1  22      Bob   27
2  33  Charlie   26
0  44    David   30
1  55      Eve   32
2  66    Frank   35
3  77  Gilbert   37

In [133]:
df3 = pd.DataFrame({"ID":[11,22,33],"Name":["Alice","Bob","Charlie"]})
df3

   ID     Name
0  11    Alice
1  22      Bob
2  33  Charlie

In [134]:
df4 = pd.DataFrame({"Fee":[1100,2200,3300],"Age":[25,27,26]})
df4

    Fee  Age
0  1100   25
1  2200   27
2  3300   26

In [135]:
stackedhorizontal = pd.concat([df3,df4],axis=1) #axis = 1 means stack it next to each other or in column wise
stackedhorizontal

   ID     Name   Fee  Age
0  11    Alice  1100   25
1  22      Bob  2200   27
2  33  Charlie  3300   26

## Merge Function

In [136]:
df5 = pd.DataFrame({"ID":[11,22,33,44],"Name":["Alice","Bob","Charlie","David"],"Salary":[25000,27000,26000,50000]})
df5

   ID     Name  Salary
0  11    Alice   25000
1  22      Bob   27000
2  33  Charlie   26000
3  44    David   50000

In [137]:
df6 = pd.DataFrame({"ID":[33,44,55,66],"Name":["Charlie","David","Eve","Frank"],"Age":[25,27,26,29]})
df6

   ID     Name  Age
0  33  Charlie   25
1  44    David   27
2  55      Eve   26
3  66    Frank   29

In [142]:
innerj = pd.merge(df5,df6,on="ID",how="inner")
innerj

   ID   Name_x  Salary   Name_y  Age
0  33  Charlie   26000  Charlie   25
1  44    David   50000    David   27

In [143]:
innerj_clean  = innerj.drop(["Name_y"],axis=1)
innerj_clean

   ID   Name_x  Salary  Age
0  33  Charlie   26000   25
1  44    David   50000   27

In [144]:
innerj_clean.columns = ["ID","Name","Sal","Age"]
innerj_clean

   ID     Name    Sal  Age
0  33  Charlie  26000   25
1  44    David  50000   27

In [145]:
leftj = pd.merge(df5,df6,on="ID",how="left")
leftj

   ID   Name_x  Salary   Name_y   Age
0  11    Alice   25000      NaN   NaN
1  22      Bob   27000      NaN   NaN
2  33  Charlie   26000  Charlie  25.0
3  44    David   50000    David  27.0

In [146]:
rightj = pd.merge(df5,df6,on="ID",how="right")
rightj

   ID   Name_x   Salary   Name_y  Age
0  33  Charlie  26000.0  Charlie   25
1  44    David  50000.0    David   27
2  55      NaN      NaN      Eve   26
3  66      NaN      NaN    Frank   29

In [147]:
outerj = pd.merge(df5,df6,on="ID",how="outer")
outerj

   ID   Name_x   Salary   Name_y   Age
0  11    Alice  25000.0      NaN   NaN
1  22      Bob  27000.0      NaN   NaN
2  33  Charlie  26000.0  Charlie  25.0
3  44    David  50000.0    David  27.0
4  55      NaN      NaN      Eve  26.0
5  66      NaN      NaN    Frank  29.0

What is the difference between concat(), merge(), and join()

## Join - same as merge but joins based on index

In [148]:
data_cust = pd.DataFrame({"Name":["Alice","Bob","Charlie","David"],"City":["XYZ","ABC","PQR","MNO"]})
data_cust

      Name City
0    Alice  XYZ
1      Bob  ABC
2  Charlie  PQR
3    David  MNO

In [149]:
data_order = pd.DataFrame({"Order_amount":[11,45,64,25],"Order_Date":["Z","C","R","O"]})
data_order

   Order_amount Order_Date
0            11          Z
1            45          C
2            64          R
3            25          O

In [150]:
data_cust.index.name = "customer_id"
data_cust

                Name City
customer_id
0              Alice  XYZ
1                Bob  ABC
2            Charlie  PQR
3              David  MNO

In [151]:
data_order.index.name = "customer_id"
data_order

             Order_amount Order_Date
customer_id
0                      11          Z
1                      45          C
2                      64          R
3                      25          O

In [152]:
join1 = data_cust.join(data_order)
join1

                Name City  Order_amount Order_Date
customer_id
0              Alice  XYZ            11          Z
1                Bob  ABC            45          C
2            Charlie  PQR            64          R
3              David  MNO            25          O

In [153]:
joinleft = data_cust.join(data_order,how="left")
joinleft

                Name City  Order_amount Order_Date
customer_id
0              Alice  XYZ            11          Z
1                Bob  ABC            45          C
2            Charlie  PQR            64          R
3              David  MNO            25          O

In [154]:
joinright = data_cust.join(data_order,how="right")
joinright

                Name City  Order_amount Order_Date
customer_id
0              Alice  XYZ            11          Z
1                Bob  ABC            45          C
2            Charlie  PQR            64          R
3              David  MNO            25          O

In [160]:
df7 = df5.set_index("ID")

In [161]:
df7

       Name  Salary
ID
11    Alice   25000
22      Bob   27000
33  Charlie   26000
44    David   50000

In [162]:
df8 = df6.set_index("ID")

In [166]:
df8.drop(["Name"],axis=1,inplace=True)

In [167]:
joinleft2 = df7.join(df8,how="left")
joinleft2

       Name  Salary   Age
ID
11    Alice   25000   NaN
22      Bob   27000   NaN
33  Charlie   26000  25.0
44    David   50000  27.0

In [170]:
joinleft2.loc[joinleft2["Name"]=="Alice","Name"] = "Ambrose"
joinleft2

       Name  Salary   Age
ID
11  Ambrose   25000   NaN
22      Bob   27000   NaN
33  Charlie   26000  25.0
44    David   50000  27.0

In [171]:
joinleft2.dropna() #drop null values

       Name  Salary   Age
ID
33  Charlie   26000  25.0
44    David   50000  27.0

In [172]:
df3

   ID     Name
0  11    Alice
1  22      Bob
2  33  Charlie

## Iterating over dataframes

In [173]:
for a,b in df3.items(): #iterate by columns
    print(a)
    print("----")
    print(b)

ID
----
0    11
1    22
2    33
Name: ID, dtype: int64
Name
----
0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object

In [174]:
for a,b in df3.iterrows(): #Iterate over rows
    print(a)
    print("----")
    print(b)

0
----
ID         11
Name    Alice
Name: 0, dtype: object
1
----
ID       22
Name    Bob
Name: 1, dtype: object
2
----
ID           33
Name    Charlie
Name: 2, dtype: object

# Groupby Function

In [181]:
# Customer DataFrame
data_cust = pd.DataFrame({
    "cust_id": [1, 2, 3, 4],
    "cust_name": ["Alka", "Ravi", "Neha", "Simran"],
    "region": ["North", "South", "North", "East"]
})

# Order DataFrame
data_order = pd.DataFrame({
    "order_id": [101, 102, 103, 104, 105],
    "cust_id": [1, 2, 1, 3, 4],
    "amount": [250, 450, 300, 200, 500]
})

data_cust

   cust_id cust_name region
0        1      Alka  North
1        2      Ravi  South
2        3      Neha  North
3        4    Simran   East

In [182]:
data_order

   order_id  cust_id  amount
0       101        1     250
1       102        2     450
2       103        1     300
3       104        3     200
4       105        4     500

In [183]:
#Example 1: Group orders by cust_id and sum amounts

order_summary = data_order.groupby("cust_id")["amount"].sum()
order_summary

cust_id
1    550
2    450
3    200
4    500
Name: amount, dtype: int64

In [184]:
#Example 2: Group customers by region and count them - How many customers per region

cust_region = data_cust.groupby("region")["cust_id"].count()
cust_region

region
East     1
North    2
South    1
Name: cust_id, dtype: int64

In [185]:
merged = pd.merge(data_cust, data_order, on="cust_id", how="inner")
merged

   cust_id cust_name region  order_id  amount
0        1      Alka  North       101     250
1        1      Alka  North       103     300
2        2      Ravi  South       102     450
3        3      Neha  North       104     200
4        4    Simran   East       105     500

In [186]:
# Groupby with aggregate function

cust_summary = merged.groupby("cust_id").agg({"amount": ["sum", "mean", "count", "max", "min"],"order_id":["count"]})
cust_summary

        amount                        order_id
           sum   mean count  max  min    count
cust_id
1          550  275.0     2  300  250        2
2          450  450.0     1  450  450        1
3          200  200.0     1  200  200        1
4          500  500.0     1  500  500        1

In [189]:
merged.groupby("region").groups

{'East': [4], 'North': [0, 1, 3], 'South': [2]}

In [191]:
merged.groupby("region").get_group("North")

   cust_id cust_name region  order_id  amount
0        1      Alka  North       101     250
1        1      Alka  North       103     300
3        3      Neha  North       104     200

In [193]:
merged.to_csv("xyz.csv")